name: Maven CI/CD

on:
  push: 
    branch: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: step-1
      uses: actions/checkout@v2
    
    - name: step-2
      run: echo hello world

    - name: setup-java
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: build package
      run: mvn build 
