name: Maven CI/CD

on:
  push: 
    branch: [master]

jobs:
  build:
    run on: ubuntu-latest

    steps:
    - name: step-1
      uses: actions/checkout@v2
    
    - name: step-2
      run: echo hello world
